flowchart LR
ECA[颈外动脉]-->FA[面动脉]
subgraph 面动脉分支
direction LR
FA-->颏下动脉
FA-->下唇动脉
FA-->上唇动脉
FA-->鼻外侧动脉
end
FA-->内眦动脉
ECA-->e[在下颌颈平面分为2个终支]
e-->MXA[上颌动脉]
e-->ATS[颞浅动脉]
ATS-->|在腮腺深面发出|面横动脉
MXA-->a[下颌段分支]
a-->IAA[下牙槽动脉]
IAA-->|进入下颌孔前分支出|下颌舌骨肌动脉
IAA-->|经颏孔穿出至颏部|颏动脉
a-->MMA[脑膜中动脉]
MMA-->b["颅骨内面分支为额、顶支"]
MXA-->c[翼肌段分支]
c-->d["分支至翼内、外肌、咬肌和颞肌"]
c-->颊动脉
MXA-->f[翼腭窝段分支]
f-->上牙槽后动脉
f-->IOA[眶下动脉]
IOA-->|在眶下管内发出|上牙槽动脉
