flowchart LR
内眦静脉-->FV[面静脉]
FV-->a
RMNV[下颌后静脉]-->a[汇合于下颌角下方]
a-->|穿颈深筋膜浅层注入|颈内静脉
FV<-->OV[眼静脉]
OV<-->CS[海绵窦]
FV<-->DFV[面深静脉]
DFV<-->CS
FV<-->PP[翼静脉丛]
PP<-->CS
颞浅静脉-->b((汇合))
与上颌动脉分支伴行静脉-->|收纳|PP
PP-->MXV
MXV[上颌静脉]-->b
b-->RMNV
RMNV-->RMNVAB[下颌后静脉前支]
RMNVAB-->c((汇合))
FV-->c
c-->ECV[颈外静脉]
RMNV-->RMNVPB[下颌后静脉后支]
RMNVPB-->d((汇合))
耳后静脉-->d
d-->ECV
