flowchart LR
MS[咬肌间隙]-->|向前|颊间隙
MS-->|向下绕过下颌切迹|翼颌间隙
MS-->|经颧弓深侧|颞窝
MS-->|向下|颌下间隙
MS-->|向后下|腮腺
MS-->|向下绕过下颌切迹|IF[颞下窝]
PS[翼下颌间隙]-->|向上|IF
PS-->|向上|翼腭窝
PS-->|向内沿翼内肌后缘|咽旁间隙
PS-->|向下|下颌后窝
PS-->|沿血管神经束向上经卵圆孔|颅腔
SS[舌下间隙]-->|向后在下颌舌骨肌群后缘处|下颌下间隙
SS-->|向后上|PS
SS-->|向前|舌骨下间隙
